// <auto-generated />
using System;
using ApiGateway.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiGateway.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiGateway.Models.CompraCab", b =>
                {
                    b.Property<int>("Id_CompraCab")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_CompraCab"));

                    b.Property<DateTime>("FecRegistro")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Igv")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id_CompraCab");

                    b.ToTable("CompraCab", (string)null);
                });

            modelBuilder.Entity("ApiGateway.Models.CompraDet", b =>
                {
                    b.Property<int>("Id_CompraDet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_CompraDet"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("Id_CompraCab")
                        .HasColumnType("int");

                    b.Property<int>("Id_producto")
                        .HasColumnType("int");

                    b.Property<decimal>("Igv")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Sub_Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id_CompraDet");

                    b.HasIndex("Id_CompraCab");

                    b.HasIndex("Id_producto");

                    b.ToTable("CompraDet", (string)null);
                });

            modelBuilder.Entity("ApiGateway.Models.MovimientoCab", b =>
                {
                    b.Property<int>("Id_MovimientoCab")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_MovimientoCab"));

                    b.Property<DateTime>("Fec_registro")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_DocumentoOrigen")
                        .HasColumnType("int");

                    b.Property<int>("Id_TipoMovimiento")
                        .HasColumnType("int");

                    b.HasKey("Id_MovimientoCab");

                    b.ToTable("MovimientoCab", (string)null);
                });

            modelBuilder.Entity("ApiGateway.Models.MovimientoDet", b =>
                {
                    b.Property<int>("Id_MovimientoDet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_MovimientoDet"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("Id_MovimientoCab")
                        .HasColumnType("int");

                    b.Property<int>("Id_Producto")
                        .HasColumnType("int");

                    b.HasKey("Id_MovimientoDet");

                    b.HasIndex("Id_MovimientoCab");

                    b.HasIndex("Id_Producto");

                    b.ToTable("MovimientoDet", (string)null);
                });

            modelBuilder.Entity("ApiGateway.Models.Producto", b =>
                {
                    b.Property<int>("Id_producto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_producto"));

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Fec_registro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre_producto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NroLote")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrecioVenta")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id_producto");

                    b.ToTable("Productos", (string)null);
                });

            modelBuilder.Entity("ApiGateway.Models.VentaCab", b =>
                {
                    b.Property<int>("Id_VentaCab")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_VentaCab"));

                    b.Property<DateTime>("FecRegistro")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Igv")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id_VentaCab");

                    b.ToTable("VentaCab", (string)null);
                });

            modelBuilder.Entity("ApiGateway.Models.VentaDet", b =>
                {
                    b.Property<int>("Id_VentaDet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_VentaDet"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("Id_VentaCab")
                        .HasColumnType("int");

                    b.Property<int>("Id_producto")
                        .HasColumnType("int");

                    b.Property<decimal>("Igv")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Sub_Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id_VentaDet");

                    b.HasIndex("Id_VentaCab");

                    b.HasIndex("Id_producto");

                    b.ToTable("VentaDet", (string)null);
                });

            modelBuilder.Entity("ApiGateway.Models.CompraDet", b =>
                {
                    b.HasOne("ApiGateway.Models.CompraCab", "CompraCab")
                        .WithMany("Detalles")
                        .HasForeignKey("Id_CompraCab")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiGateway.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("Id_producto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompraCab");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("ApiGateway.Models.MovimientoDet", b =>
                {
                    b.HasOne("ApiGateway.Models.MovimientoCab", "MovimientoCab")
                        .WithMany("Detalles")
                        .HasForeignKey("Id_MovimientoCab")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiGateway.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("Id_Producto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MovimientoCab");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("ApiGateway.Models.VentaDet", b =>
                {
                    b.HasOne("ApiGateway.Models.VentaCab", "VentaCab")
                        .WithMany("Detalles")
                        .HasForeignKey("Id_VentaCab")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiGateway.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("Id_producto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("VentaCab");
                });

            modelBuilder.Entity("ApiGateway.Models.CompraCab", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("ApiGateway.Models.MovimientoCab", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("ApiGateway.Models.VentaCab", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
